### ISSUE TITLE
Custom field name in validations (i18n)

### ISSUE THREAD

**Issue by ozziest** [axe-api/axe-api#136]
Developers should be able to add custom field names to the validation messages.

### Motivation

Currently, developers are able to add multiple languages to the API. It works like the following example in form validations;

```json
{
  "errors": {
    "email": ["Das email Feld muss ausgefüllt sein."],
    "name": ["Das name Feld muss ausgefüllt sein."],
    "surname": ["Das surname Feld muss ausgefüllt sein."]
  }
}
```

As you can see, all validations messages are in German except the `field` name. Developers should be able to manage this field name for form validations.

> Also, we can use these field names in documentation sections.

### Definitions

All translations should be defined the under the `locales` folders by the language code.

For example, `locales/en/fields.yaml`

```yaml
email: Email address
phone: Phone
name: Name
surname: Surname
```

These values should be used by the form validation library like the following example;

```js
let validator = new Validator({ name: '' }, { name: 'required' });
validator.setAttributeNames({ name: 'custom_name' });
if (validator.fails()) {
  validator.errors.first('name'); // "The custom_name field is required."
}
```

### Custom Translations

Developers should be able to use custom translations. `fields.yaml` file will be used by the Axe API. But the other files should be able to use the following example;

```js
const onBeforeInsert = async ({ t }: IHookParameter) => {
  t("user.gmail_is_not_accepted")
};
```

> `gmail_is_not_accepted` key should be located under the `user.yml` locales files.

**Comment by ozziest** [comment]
@saracalihan, I would like to hear your opinions about this template. Does it look good enough?

**Comment by saracalihan** [comment]
> @saracalihan, I would like to hear your opinions about this template. Does it look good enough?

It sounds like a very useful feature, but I have some questions.

+ First, can "validator" be used only for validation for localization or is this control HTTP body like [Joi](https://www.npmjs.com/package/joi)? I think the validator can validate both, it seems more powerful.

+ Why do we use YAML instead of JSON file type? Is it easier to read the JSON from the code and for the JS developer? The JSON scenario is more efficient eg I have a custom locale like "user.yml" and a single field like "gmail_is_not_accepted", as a developer I don't want to create a file just for that field. import on code.

Apart from these questions, it is enough for me for custom localization.

**Comment by ozziest** [comment]
@saracalihan, thank you very much for your feedback. 🤗 


> First, can "validator" be used only for validation for localization or is this control HTTP body like [Joi](https://www.npmjs.com/package/joi)? I think the validator can validate both, it seems more powerful.

In Axe API, we use [validatorjs](https://github.com/mikeerickson/validatorjs) library. The reason we use `validatorjs` is defining the validation rules is very easy. We just pass the validations rules from the model files to the `validatorjs` library. In `Joi`, Axe API has to transform all the validation rules to the `Joi` functions. About this issue, we should provide field names to the `validatorjs` to get perfect translated messages. 

> Why do we use YAML instead of JSON file type? Is it easier to read the JSON from the code and for the JS developer?

I think the YAML is very clear than JSON. But of course, we can use JSON. That's totally fine. 

> The JSON scenario is more efficient eg I have a custom locale like user.yml and a single field like gmail_is_not_accepted, as a developer I don't want to create a file just for that field, i can import on code directly.

As a developer, you need more fields than one field if you want to support multiple languages at the same time, in reality. Also, developers are not able to manage the validating process. Let's look at the following example;

```js
class Users extends Model {
  get validations(): Record<string, string> {
    return {
      email: "required|email",
      name: "required|max:50",
      surname: "required|max:50",
      age: "max:100",
    };
  }
}
```

This is the only thing a developer should do to validate data. As you can notice, there is no way to define fields name in different languages. Also, a developer might want to throw some special error messages to the users. For example; `You can not use Gmail as a mail address.`. Eventually, developers might need to define many things in locales such as field names and custom messages. 

Does it make sense to you?

**Comment by saracalihan** [comment]
@ozziest You are right about JSON, It becomes difficult to write when dealing with square brackets, quotes.

i get to point, now this flex and usage is okay to me.

**Comment by ozziest** [comment]
I decided to use `json` files. 

However, we have a problem with the validation library. It sets the language as a global value. Which doesn't allow to clients use different languages at the same time. [Check this out](https://github.com/mikeerickson/validatorjs?tab=readme-ov-file#language-support)

We can't import this feature without replacing the validation library.

**Comment by ozziest** [comment]
This feature won't be implemented. Because the current validation library has several issues. ([1](https://github.com/axe-api/axe-api/issues/136#issuecomment-1949107014), [2](https://github.com/axe-api/axe-api/issues/368)). 

Instead of that, [robust-validator](https://github.com/axe-api/validator) library support [has been added](https://github.com/axe-api/axe-api/pull/369). And it doesn't need fields names because it allows to handle field name in the frontend side.

So I close this issue.
