### ISSUE TITLE
"all" keyword should be added to the reserved keys

### ISSUE THREAD

**Issue by ozziest** [axe-api/axe-api#230]
## Motivation

`all` keyword should be added to the reserved keys.

## Technical Details

`RESERVED_KEYWORDS` in `constants.ts`

**Comment by tarunsamanta2k20** [comment]
I'd like to work on it

**Comment by ozziest** [comment]
Hi @tarunsamanta2k20! That's great. 🥳 

Just we need to change the following file; https://github.com/axe-api/axe-api/blob/master/src/constants.ts#L21
The `all` keyword should be added to the `RESERVED_KEYWORDS`. 

Please let me know if you need any help. 🤗
