### ISSUE TITLE
Update (Put) Method Not Working ?

### ISSUE THREAD

**Issue by volkankoc** [axe-api/axe-api#281]
The update is in progress. But the app crashes
![image](https://github.com/axe-api/axe-api/assets/22777823/963ca815-206a-41f9-81c3-8b14ea69fcb1)

**Comment by ozziest** [comment]
@volkankoc this is related to missing Redis connection. I will clarify the error message. Also, I will fix the crash issue. The new version will be released today.  ☺️ 

Thank you very much for the report. ❤️

**Comment by ozziest** [comment]
To solve the issue, update the `axe-api` version to `^1.0.2`.
