### ISSUE TITLE
Ignore feature on models for creating routes

### ISSUE THREAD

**Issue by ozziest** [axe-api/axe-api#32]
As a developer, I should be able to hide a model in auto-created routes. 

```js
import { Model } from "axe-api"

class User extends Model {
  get ignore() {
    return true
  }
}

export default User
```

Obviously, we can use the [handlers](https://axe-api.github.io/03-routes/#handlers) method to manage this. But the `ignore()` method would be easier. 

> Client should be able to use those models in [related queries](https://axe-api.github.io/05-queries/#relation-queries).

**Comment by vaish567** [comment]
Howdy @ozziest If you don't mind me to step-up on this issue? If you haven't assign this ToDo issue?

**Comment by ozziest** [comment]
Hi @vaish567, welcome to the board. 🥳 The issue is yours. 

We haven't created good documentation yet but you can use [dev-api](https://github.com/axe-api/dev-api) repository for your development environment. Also, if you have any questions please let me know. If you can create something about it but you may not be sure, please open a Draft PR, so I can review it to help you.

Thank you very much for your help. 🥇

**Comment by vaish567** [comment]
Hello @ozziest Should I use model in `Model.js` ?

> As a developer, I should be able to hide a model in auto-created routes.
> 
> ```js
> import { Model } from "axe-api"
> 
> class User extends Model {
>   get ignore() {
>     return true
>   }
> }

**Comment by ozziest** [comment]
Hello @vaish567, yes. But the default value should be `false` in Model.js. If the developer wants they can make it true n their models.
