### ISSUE TITLE
Making optional the default API response

### ISSUE THREAD

**Issue by ozziest** [axe-api/axe-api#6]
For now, the default API response is something like that;

```json
{
  "name": "AXE API",
  "description": "The best API creation tool in the world.",
  "aim": "To kill them all!"
}
```

But nobody has to use that schema. Developers should be able to select what kind of response should be given. To do that, I suggest that to add a new property to the `app/Config/Application.js` file like the following code;

```js
import { LOG_LEVEL } from "axe-api";

export default async () => {
  return {
    env: process.env.NODE_ENV,
    port: process.env.APP_PORT,
    logLevel: LOG_LEVEL.INFO,
    defaultResponse: {
      "name": "AXE API",
      "description": "The best API creation tool in the world.",
      "aim": "To kill them all!"
    },
  };
};
```

With that, developers can decide what they want to show. 

> In this issue, we should update the axe-api-template project, too.

**Comment by ozziest** [comment]
@YusufSina , can you handle this?

**Comment by YusufSina** [comment]
> @YusufSina , can you handle this?

Sure, easy peasy :)

**Comment by ozziest** [comment]
We worked on it this issue so much and tried to understand what really we need. 

As a result of this working process, we decided to remove all default HTTP resources from the core structure. Instead of that, we are going to add the following code example to the [axe-api-template](https://github.com/axe-api/axe-api-template);

```js
const onBeforeInit = async ({ app }) => {
  app.get('/', (req, res) => {
    res.json({
      "name": "AXE API",
      "description": "The best API creation tool in the world.",
    })
  })
};

const onAfterInit = async ({ app }) => {};

export { onBeforeInit, onAfterInit };
```
